version: '2.0'

services:
     mysql_oauth2:
       image: mysql:5.6
       ports:
           - '3306:3306'
       volumes:
           - './data:/var/lib/mysql'
       restart: always
       environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: oauth2
     app:
       build: ./
       ports:
         - '8080:8080'
       restart: always
       links:
         - mysql_oauth2



